### ISSUE TITLE
What exactly is DQN is optimizing?

### ISSUE THREAD

**Issue by codebro634** [automl-edu/RL_lecture#28]
![img](https://user-images.githubusercontent.com/55958538/141508680-011d091e-2f56-4ec9-a1b6-92aa635772e2.png)

The function we were optimizing for policy evaluation is this one here. In the slides it was mentioned that in DQN we are also using SGD to optimize some function. But I'm having trouble understanding what that function is exactly in the DQN case. If we used a similar formula like the one i posted here, it is completely unclear for me from which distrubtion we are sampling if it is a fixed one. And sampling from our current policy also can't work since the policy depends on our current weights i.e. we can't interchange gradient and expectation.

**Comment by mlindauer** [comment]
You are completely right. It is in fact not a very sound solution to the problem that we do not have a single distribution we sample from, but in fact, we put simply put all observations into our reply buffer and sample from it. That's completely ignores that the distribution changes actually since we also update \pi in a regular base.
